name = "moontv-register-bot"
main = "_worker.js"
compatibility_date = "2024-08-01"
keep_vars = true

# 环境变量配置（可在 Cloudflare 控制台或此处配置）
[vars]
MISUB_BASE = "https://subhub.tsmoe.com"
SUBSTORE_BASE = "https://substore.tsmoe.com"
SUBSTORE_NAME = "relay"
# 管理专用参数（仅在控制台或这里配置后生效）
# ADMIN_TG_ID = "123456789"            # 你的 Telegram 数字ID
# ADMIN_TOKEN = "your_admin_token"      # 受保护HTTP接口访问令牌
# BOT_TOKEN = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
# GROUP_ID = "-1001234567890"
# MOONTVURL = "https://moontv.dedyn.io"
# APIURL = "https://tcp.sg-members-1.clawcloudrun.com"
# USERNAME = "admin"
# PASSWORD = "admin_password"
# TOKEN = "token"

# [[kv_namespaces]]
# binding = "KV"
# id = "1fdae7a5eb774135832f55d461ac81e3"

# 定时触发（需要绑定到Cloudflare计划内的Cron）
# [[triggers.crons]]
# schedule = "0 3 * * *"   # 每天 03:00 UTC 触发，推送Top-N日报
